version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: '23:00'
    timezone: America/New_York
  open-pull-requests-limit: 10
  labels:
  - dependencies
