name: test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: [10.x, 12.x, 13.x, 14.x]

    steps:
      - name: Checkout source code
        uses: actions/checkout@v1

      - name: Setup Node v${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        run: yarn install

      - name: Flow
        run: yarn run -s flow check

      - name: Jest
        run: yarn run -s jest --passWithNoTests --coverage

      - name: Eslint
        run: yarn run -s eslint --report-unused-disable-directives src

      - name: Import-sort
        run: yarn run -s import-sort --list-different 'src/**/*.js'

      - name: Prettier
        run: yarn run -s prettier --check 'src/**/*.js'
