name: test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: [10.x, 12.x, 13.x, 14.x]

    steps:
      - name: Checkout source code
        uses: actions/checkout@v1

      - name: Setup Node v${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        run: yarn install

      - name: Run tests
        run: yarn test
